// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUjIFaQbji5HtyTf6cqmQzRS9j-Zxqx4',
    appId: '1:1082906545283:web:b4d0668ff1de740a659fb6',
    messagingSenderId: '1082906545283',
    projectId: 'taxi-a30eb',
    authDomain: 'taxi-a30eb.firebaseapp.com',
    databaseURL: 'https://taxi-a30eb-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-a30eb.appspot.com',
    measurementId: 'G-T08TL50ZTY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkqXkRO9gM0BqaRFo3u1_j5u70jIWqIPM',
    appId: '1:1082906545283:android:4999f2cf9c2d030c659fb6',
    messagingSenderId: '1082906545283',
    projectId: 'taxi-a30eb',
    databaseURL: 'https://taxi-a30eb-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-a30eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA37HlfhheAH31CBCQGJ159UWisEsWRp1c',
    appId: '1:1082906545283:ios:7745ac8679371c69659fb6',
    messagingSenderId: '1082906545283',
    projectId: 'taxi-a30eb',
    databaseURL: 'https://taxi-a30eb-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-a30eb.appspot.com',
    iosBundleId: 'bundle.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA37HlfhheAH31CBCQGJ159UWisEsWRp1c',
    appId: '1:1082906545283:ios:f054d42b9e965f84659fb6',
    messagingSenderId: '1082906545283',
    projectId: 'taxi-a30eb',
    databaseURL: 'https://taxi-a30eb-default-rtdb.firebaseio.com',
    storageBucket: 'taxi-a30eb.appspot.com',
    iosBundleId: 'com.example.flutterUser.RunnerTests',
  );
}
