// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0apv2TKUgWJ5ZE2nl4PrzbmT1aloxqAI',
    appId: '1:957033296631:web:4b6d12c26e8ab38d26d9f2',
    messagingSenderId: '957033296631',
    projectId: 'pony-a861f',
    authDomain: 'pony-a861f.firebaseapp.com',
    storageBucket: 'pony-a861f.appspot.com',
    measurementId: 'G-HFBMS94KQE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBproo3KGKdaUSrjsarU_OfDe73mSfaBNw',
    appId: '1:957033296631:android:f051328dc990e64e26d9f2',
    messagingSenderId: '957033296631',
    projectId: 'pony-a861f',
    storageBucket: 'pony-a861f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwkX8QBzpbomfJvpCecyCK_ue-iBwxWiw',
    appId: '1:957033296631:ios:ed5f125daedeaad826d9f2',
    messagingSenderId: '957033296631',
    projectId: 'pony-a861f',
    storageBucket: 'pony-a861f.appspot.com',
    iosBundleId: 'bundle.id',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwkX8QBzpbomfJvpCecyCK_ue-iBwxWiw',
    appId: '1:957033296631:ios:2c19375d08b11f8926d9f2',
    messagingSenderId: '957033296631',
    projectId: 'pony-a861f',
    storageBucket: 'pony-a861f.appspot.com',
    iosBundleId: 'com.example.flutterUser.RunnerTests',
  );
}
